### ISSUE TITLE
Latest commit broke SendGrid\Client

### ISSUE THREAD

**Issue by Michal-sk** [sendgrid/php-http-client#88]
#### Issue Summary

The latest commit breaks sending emails.

The latest commit:
https://github.com/sendgrid/php-http-client/commit/cc7138bef4475c37296239dae450e423c11a22cf

Env:
PHP7.2

#### Steps to Reproduce

Run composer update on sengrid\sendgrid package

#### Technical details:

PHP Notice:  Object of class SendGrid\Client could not be converted to int in /srv/www/api/vendor/sendgrid/php-http-client/lib/Client.php on line 269

**Comment by cloned** [comment]
This happens to me too. Though `lib/Client.php#makeRequest()` calls `$this->prepareResponse()`, `$this->prepareResponse()` does not exist in the class (v3.9.0).

I beleive that `prepareResponse` which was commited in [d42ae6a](https://github.com/sendgrid/php-http-client/commit/d42ae6acb8472e0dd1284f74d5b39a0258d9e73f) should be in `lib/Client.php`.

It is difficult to see the reason of this error because `lib/Client.php#__call()` responds itself instead of occuring a fatal error such as "undefined method".

**Comment by 4rthem** [comment]
Same here.
It seems https://github.com/sendgrid/php-http-client/commit/d42ae6acb8472e0dd1284f74d5b39a0258d9e73f was badly merged into master.

**Comment by thinkingserious** [comment]
Thanks @Michal-sk, @cloned, @4rthem for the heads up!

I'll dig in and get this fixed today; however, it will be a few hours before I can do that. 

If you like, a PR would be most welcome, otherwise, I'll update you all here with the fix later today. Just please let us all know so we are not duplicating efforts. I'll do the same.

With Best Regards,

Elmer

**Comment by Michal-sk** [comment]
I didnt find the specfic commit. I see other comments did. I did the workaround aswel by setting a hard 3.8 in my composer

**Comment by mpetrovich** [comment]
We're experiencing the same issue.

**Comment by thinkingserious** [comment]
I've put in a PR here #89. If anyone has time, a quick code review would be most appreciated! Thanks!

**Comment by thinkingserious** [comment]
Please try version 3.9.1. Thanks!
